#!/bin/sh
players="kew,fooyin,DeaDBeeF,Feishin"
status=$(playerctl -p $players status 2>/dev/null)

case "$status" in
    Playing) icon="▶" ;;
    Paused)  icon="⏸" ;;
    Stopped) exit 0 ;;  # Nothing is playing, so no output
    *)       icon="❓" ;;
esac
echo "$icon"