#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

exec ~/.fehbg &
exec picom --experimental-backends &
exec /usr/bin/emacs --daemon &
exec xclip &
exec dunst &
exec syncthing &
exec mpd &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         3
bspc config focused_border_color "#F8F8F2"
bspc config normal_border_color "#282A36"
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
