
[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[general]
import = ["/home/nightwing/.config/alacritty/gruvbox_dark.toml"]

[font]
size = 14

[font.bold]
family = "Monaspace Krypton"
style = "Medium"

[font.italic]
family = "Monaspace Krypton"
style = "italic"

[font.normal]
family = "Monaspace Krypton"
style = "Medium"

[window]
dynamic_padding = true
decorations = "none"
# opacity = 0.9


[window.padding]
x = 20
y = 20

[keyboard]
